### ISSUE TITLE
"ImportError: cannot import name 'json'" when debugging with pydevd

### ISSUE THREAD

**Issue by 4lph4-Ph4un** [pytest-dev/pytest-flask#78]
Hi!
I'm receiving this error when attempting to debug with a pydevd -debugger.

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.1.3\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2018.1.3\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2018.1.3\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2018.1.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Program Files\JetBrains\PyCharm 2018.1.3\helpers\pycharm\_jb_pytest_runner.py", line 31, in <module>
    pytest.main(args, plugins_to_load)
  File "D:\Projects\Python\FlaskSQLAlchemyMasterClass\lib\site-packages\_pytest\config.py", line 54, in main
    config = _prepareconfig(args, plugins)
  File "D:\Projects\Python\FlaskSQLAlchemyMasterClass\lib\site-packages\_pytest\config.py", line 167, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "D:\Projects\Python\FlaskSQLAlchemyMasterClass\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "D:\Projects\Python\FlaskSQLAlchemyMasterClass\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "D:\Projects\Python\FlaskSQLAlchemyMasterClass\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "D:\Projects\Python\FlaskSQLAlchemyMasterClass\lib\site-packages\pluggy\callers.py", line 196, in _multicall
    gen.send(outcome)
  File "D:\Projects\Python\FlaskSQLAlchemyMasterClass\lib\site-packages\_pytest\helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "D:\Projects\Python\FlaskSQLAlchemyMasterClass\lib\site-packages\pluggy\callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "D:\Projects\Python\FlaskSQLAlchemyMasterClass\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "D:\Projects\Python\FlaskSQLAlchemyMasterClass\lib\site-packages\_pytest\config.py", line 981, in pytest_cmdline_parse
    self.parse(args)
  File "D:\Projects\Python\FlaskSQLAlchemyMasterClass\lib\site-packages\_pytest\config.py", line 1146, in parse
    self._preparse(args, addopts=addopts)
  File "D:\Projects\Python\FlaskSQLAlchemyMasterClass\lib\site-packages\_pytest\config.py", line 1098, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "D:\Projects\Python\FlaskSQLAlchemyMasterClass\lib\site-packages\pluggy\__init__.py", line 397, in load_setuptools_entrypoints
    plugin = ep.load()
  File "D:\Projects\Python\FlaskSQLAlchemyMasterClass\lib\site-packages\pkg_resources\__init__.py", line 2318, in load
    return self.resolve()
  File "D:\Projects\Python\FlaskSQLAlchemyMasterClass\lib\site-packages\pkg_resources\__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "D:\Projects\Python\FlaskSQLAlchemyMasterClass\lib\site-packages\_pytest\assertion\rewrite.py", line 216, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "D:\Projects\Python\FlaskSQLAlchemyMasterClass\lib\site-packages\pytest_flask\plugin.py", line 11, in <module>
    from flask import json
ImportError: cannot import name 'json'
```

**Comment by northernSage** [comment]
Hey there @4lph4-Ph4un, we will need more info (such as your code and details on your development environment) to find out what is going on. I will be closing this for now, but feel free to reopen and provide a minimal, reproducible example.
